Traceback (most recent call last):
  File "pyg.py", line 22, in <module>
  File "runpy.pyc", line 240, in run_path
  File "runpy.pyc", line 82, in _run_module_code
  File "runpy.pyc", line 72, in _run_code
  File "application.py", line 2, in <module>
    import vertex
ImportError: No module named vertex
Traceback (most recent call last):
  File "pyg.py", line 22, in <module>
  File "runpy.pyc", line 240, in run_path
  File "runpy.pyc", line 82, in _run_module_code
  File "runpy.pyc", line 72, in _run_code
  File "application.py", line 2, in <module>
    import vertex
ImportError: No module named vertex
Traceback (most recent call last):
  File "pyg.py", line 22, in <module>
  File "runpy.pyc", line 240, in run_path
  File "runpy.pyc", line 82, in _run_module_code
  File "runpy.pyc", line 72, in _run_code
  File "application.py", line 76, in <module>
    application = Application()        
  File "application.py", line 9, in __init__
    self.display()
  File "application.py", line 29, in display
    self.vertices.add(Vertex(pygame.mouse.get_pos()))
  File "application.py", line 57, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)
Traceback (most recent call last):
  File "pyg.py", line 22, in <module>
  File "runpy.pyc", line 240, in run_path
  File "runpy.pyc", line 82, in _run_module_code
  File "runpy.pyc", line 72, in _run_code
  File "application.py", line 76, in <module>
    application = Application()        
  File "application.py", line 9, in __init__
    self.display()
  File "application.py", line 29, in display
    self.vertices.add(Vertex(pygame.mouse.get_pos()))
  File "application.py", line 57, in __init__
    super(self).__init__()
TypeError: must be type, not Vertex
Traceback (most recent call last):
  File "pyg.py", line 22, in <module>
  File "runpy.pyc", line 239, in run_path
  File "runpy.pyc", line 215, in _get_code_from_file
IOError: [Errno 2] No such file or directory: 'application.py'
